name: "SR Voice Assistant"
description: "Google STT, TTS 서버 (REST API + Wyoming Protocol)"
version: "1.2.1"
slug: "sr_voice_assistant"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
ports:
  5007/tcp: 5007
  10300/tcp: 10300
  10400/tcp: 10400
ports_description:
  5007/tcp: "REST API 포트"
  10300/tcp: "Wyoming STT 포트"
  10400/tcp: "Wyoming TTS 포트"
options:
  api_port: 5007
  stt_wyoming_port: 10300
  tts_wyoming_port: 10400
  language: "ko-KR"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "dooly"
  mqtt_password: "zz0303"
  mqtt_discovery_prefix: "homeassistant"
schema:
  api_port: int
  stt_wyoming_port: int
  tts_wyoming_port: int
  language: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: password?
  mqtt_discovery_prefix: str?