name: "SR Voice Assistant"
description: "Google STT, TTS 서버 (REST API + Wyoming Protocol)"
version: "1.2.0"
slug: "sr_voice_assistant"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
ports:
  5006/tcp: 5006
  10400/tcp: 10400
ports_description:
  5006/tcp: "REST API 포트"
  10400/tcp: "Wyoming Protocol 포트 (HA 음성 어시스턴트)"
options:
  port: 5006
  language: "ko"
  ha_ip: "192.168.219.111"
schema:
  port: int
  language: str
  ha_ip: str
  api_token: str