name: "SR Voice Assistant"
description: "Google STT, TTS 서버 (Wyoming Protocol)"
version: "1.4.1"
slug: "sr_voice_assistant"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
ports:
  10300/tcp: 10300
  10400/tcp: 10400
ports_description:
  10300/tcp: "Wyoming STT 포트"
  10400/tcp: "Wyoming TTS 포트"
options:
  language: "ko"
  ha_ip: "192.168.219.111"
  api_token: ""
schema:
  language: str
  ha_ip: str
  api_token: str